
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "analysis_lib"
version = "0.1.0"
description = "Modulare Python-Bibliothek für Analysis und Visualisierung"
authors = [{name = "Dein Name"}]
requires-python = ">=3.8"
